### PR TITLE
Initialize Playground

### PR DESCRIPTION
**Pull request by nilshah98**
Features added -
1. Display highlighted code based on the language provided
2. Provide a dynamic link to pre-filled pytutor visualization based on the code and language selected

### CODE REVIEW

**Comment by abhishekgupta92** [comment]
Does it work for Javascript as well?

Abhishek Gupta ***@***.***>
CEO & Co-founder
Read about us at Forbes India 30u30
<https://www.forbesindia.com/article/30-under-30-2020/navgurukul-cracking-the-code-to-success/57717/1>
, TOI
<https://timesofindia.indiatimes.com/home/sunday-times/these-school-dropouts-have-cracked-the-code-to-a-better-life/articleshow/71458732.cms>
or
follow our blog <http://medium.com/navgurukul> for regular updates. You can
contribute using navgurukul.org/donate. Each rupee matters.

**Comment by nilshah98** [comment]
It should.
Let me add an example of JS as well.

**Comment by abhishekgupta92** [comment]
https://www.merakilearn.org/course/137/exercise/3559

There are already some examples. Can you share some links for python and
javascript on dev server?

Abhishek Gupta ***@***.***>
CEO & Co-founder
Read about us at Forbes India 30u30
<https://www.forbesindia.com/article/30-under-30-2020/navgurukul-cracking-the-code-to-success/57717/1>
, TOI
<https://timesofindia.indiatimes.com/home/sunday-times/these-school-dropouts-have-cracked-the-code-to-a-better-life/articleshow/71458732.cms>
or
follow our blog <http://medium.com/navgurukul> for regular updates. You can
contribute using navgurukul.org/donate. Each rupee matters.

**Comment by nilshah98** [comment]
@abhishekgupta92 Can you check now ?
I have integrated this to the exercises content.

Edit: if this looks good, then I will clean up, ie. remove the playground menu option.

**Pull request closed without merging**
