### PR TITLE
Revert "Fix/select radio"

### PR DESCRIPTION
**Pull request by komalahire**
Reverts navgurukul/bhanwari-devi#224

### CODE REVIEW

**Comment by komalahire** [comment]
Sorry @jschanker , I merged PR by mistakenly, so reverted the changes, can you please review

**Comment by jschanker** [comment]
@komalahire Sure, but I don't think I can make suggestions on deleted lines.  If you first merge this pull request and then revert this reverted commit and open a new pull request for it, I'll probably be able to make suggestions that you can commit.   Alternatively, I can a open a new pull request, whichever you think is best. @Poonam-Singh-Bagh

**Comment by Poonam-Singh-Bagh** [comment]
@jschanker can you please review it?

**Comment by Poonam-Singh-Bagh** [comment]
@jschanker we revert it but however, the changes didn't get reverted, the changes got merged into main. It's in production now.

**Comment by jschanker** [comment]
@Poonam-Singh-Bagh To elaborate, since this pull request reverts your addition of the following lines, they are marked as deleted in this pull request:
https://github.com/navgurukul/bhanwari-devi/blob/379e027fcbc9738ab246691d6f103d52a3b1242a/src/components/Class/index.js#L350-L356

Because they no longer appear in the code from this branch, I can't make a suggestion on them.  So, for me to review, you can create a new branch based off of this one (revert-224-fix/select-radio) where you revert the undo, which will essentially be a redo of the commit where you added these lines.  Then, the diff will show these lines in green, so if you open a PR asking to merge the new branch into this one (revert-224-fix/select-radio), I can make the suggestion on these lines.  You can then make commits accepting those suggestions on that new branch and merge that branch into this one.  Then this branch will contain your original changes with my suggestions so you'll be able to merge this PR into production (main).  

But I don't know if doing all that is worth it, so I can just make a PR directly off main where I make the changes I suggested.  Or, since my suggestions were for minor changes anyway, we can just leave the main branch as is, whichever you and @komalahire think is best.

**Comment by Poonam-Singh-Bagh** [comment]
@jschanker I had made changes after revert that you have suggested and had pushed the code on the same branch `fix/selete-radio`. If we need to do it again then as you're saying you can do it then please do it.

Screenshot from 2022-01-21 16-56-21

Screenshot from 2022-01-21 16-52-37

**Pull request closed without merging**
